CREATE TABLE IF NOT EXISTS reviews
(
    review_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     varchar,
    is_positive boolean,
    user_id     integer,
    film_id     integer,
    useful      integer
);

ALTER TABLE reviews
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE reviews
    ADD FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;
