CREATE TABLE IF NOT EXISTS feed
(
    event_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  integer,
    entity_id integer,
    event_type varchar,
    operation  varchar,
    timestamp bigint

);
ALTER TABLE feed
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ;
